Update post-discord.yml

diff --git a/.github/workflows/post-discord.yml b/.github/workflows/post-discord.yml
--- a/.github/workflows/post-discord.yml
+++ b/.github/workflows/post-discord.yml
@@ -7,66 +7,66 @@ on:
 #linter
 
 jobs:
-  which_branch:
-    runs-on: ubuntu-latest
-    steps:
-      # extract branch name
-      - name: Extract branch name
-        if: github.event_name != 'pull_request'
-        shell: bash
-        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
-        id: extract_branch
+#   which_branch:
+#     runs-on: ubuntu-latest
+#     steps:
+#       # extract branch name
+#       - name: Extract branch name
+#         if: github.event_name != 'pull_request'
+#         shell: bash
+#         run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
+#         id: extract_branch
 
-      # extract branch name on pull request
-      - name: Print branch name
-        if: github.event_name == 'pull_request'
-        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"
+#       # extract branch name on pull request
+#       - name: Print branch name
+#         if: github.event_name == 'pull_request'
+#         run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"
 
-      # print branch name
-      - name: Get branch name
-        run: echo 'The branch name is' $BRANCH_NAME
-  one:
-    runs-on: ubuntu-latest
-    outputs:
-      test: ${{ steps.step1.outputs.test }}    
-    strategy:
-      matrix:
-        os: [1, 2]
-    steps:
-    - name: fail
-      id: step0
-      run: exit(1)
-#       continue-on-error: true
-    - id: step1
-      if: always()
-      run: |
+#       # print branch name
+#       - name: Get branch name
+#         run: echo 'The branch name is' $BRANCH_NAME
+#   one:
+#     runs-on: ubuntu-latest
+#     outputs:
+#       test: ${{ steps.step1.outputs.test }}    
+#     strategy:
+#       matrix:
+#         os: [1, 2]
+#     steps:
+#     - name: fail
+#       id: step0
+#       run: exit(1)
+# #       continue-on-error: true
+#     - id: step1
+#       if: always()
+#       run: |
       
-        var1=$([ -z "${{steps.step1.outputs.test}}" ] && echo "[]" || echo "${{steps.step1.outputs.test}}")
-        echo "var1::$var1"
-        var2=$(echo "$var1" | jq '. += ["${{ matrix.os }}"]')
-        echo "var2::$var2"
-        echo "set-output"
-        echo ::set-output name=test::$var
-    - name: test1
-      id: step2
-      run: echo "test1"
-    - name: test2
-      id: step3
-      if: failure()
-      run: |
-       echo '${{ toJson(steps.step0) }}'
-       echo '${{ toJson(steps.step1) }}'
-       echo '${{ toJson(steps.step2) }}'
-       echo '${{ toJson(steps.step3) }}'
-       echo '${{ toJson(steps) }}' | jq  'del(.[].outputs)' | jq  'del(.[].conclusion)'
-       echo '${{ toJson(steps.*.outcome) }}'
+#         var1=$([ -z "${{steps.step1.outputs.test}}" ] && echo "[]" || echo "${{steps.step1.outputs.test}}")
+#         echo "var1::$var1"
+#         var2=$(echo "$var1" | jq '. += ["${{ matrix.os }}"]')
+#         echo "var2::$var2"
+#         echo "set-output"
+#         echo ::set-output name=test::$var
+#     - name: test1
+#       id: step2
+#       run: echo "test1"
+#     - name: test2
+#       id: step3
+#       if: failure()
+#       run: |
+#        echo '${{ toJson(steps.step0) }}'
+#        echo '${{ toJson(steps.step1) }}'
+#        echo '${{ toJson(steps.step2) }}'
+#        echo '${{ toJson(steps.step3) }}'
+#        echo '${{ toJson(steps) }}' | jq  'del(.[].outputs)' | jq  'del(.[].conclusion)'
+#        echo '${{ toJson(steps.*.outcome) }}'
        
         
-  two:
-    runs-on: ubuntu-latest
-    needs: one
-    steps:
-    - run: echo '${{ toJson(needs) }}'
+#   two:
+#     runs-on: ubuntu-latest
+#     needs: one
+#     steps:
+#     - run: echo '${{ toJson(needs) }}'
 
 
 
@@ -77,10 +77,10 @@ jobs:
       - name: Discord notification
         env:
           DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
-          DISCORD_EMBEDS: '[{"color":39423,"title":"Some title","description":"Some description here","thumbnail":{"url":"https://i.imgur.com/AfFp7pu.png"},"fields":[{"name":"Regular field title","value":"Some value here"},{"name":"dbvdsb​","value":"​vdsvds","inline":false},{"name":"Inline field title","value":"Some value here","inline":true},{"name":"Inline field title","value":" Some value here","inline":true},{"name":"Inline field title","value":"Some value here","inline":true}],"image":{"url":"https://i.imgur.com/AfFp7pu.png"},"footer":{"title": "Some title","text":"Some footer text here"}}]'
+          DISCORD_EMBEDS: '[{"color":39423,"title":"Some title","description":"Some description here","thumbnail":{"url":"https://i.imgur.com/AfFp7pu.png"},"fields":[{"name":"Regular field title","value":"Some value here"},{"name":"dbvdsb​","value":"​vdsvds","inline":false},{"name":"Inline field title","value":"Some value here","inline":true},{"name":"Inline field title","value":" Some value here","inline":true},{"name":"Inline field title","value":"Some value here","inline":true}],"image":{"url":"https://i.imgur.com/AfFp7pu.png"},"footer":{"title": "Some title","text":"Some footer 1text here"}}]'
           
           #,,"thumbnail":{"url":"https://i.imgur.com/AfFp7pu.png"},}
           #'[{"title":"Meow!","color":1127128},{"title":"Meow-meow!","color":14177041}]'
         uses: Ilshidur/action-discord@0.3.2
-        with:
-          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
+#         with:
+#           args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
